apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    type: back-end
spec:
   containers: 
    - name: hello-world
      image: busybox
      command:
        - 'sh'
        - '-c'
        - 'echo Hello world! from Dheeraj && sleep 3600'
      resources:
        limits:
         memory: "32Mi"
         cpu: "64m"